baseURL = 'https://nodd0737.github.io/'
languageCode = 'en-us'
title = "Nodd's Personal Website"
publishDir = "public"

theme = ["PaperMod", "hugo-admonitions"]

[languages.en]
  languageName = "English"
  weight = 1
  title = "Nodd's Personal Website"
  languageCode = "en-us"
  contentDir = "content/"

  [[languages.en.menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[languages.en.menu.main]]
    name = "Math"
    url = "/categories/math/"
    weight = 2

  [[languages.en.menu.main]]
    name = "Others"
    url = "/categories/others/"
    weight = 3

  [[languages.en.menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[languages.en.menu.main]]
    name = "Search"
    url = "/search/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[params]
  math = true
  homeInfoParams = {Title = "Welcome!", Content = "This is my site for sharing math and other reflections."}
  defaultTheme = "auto"
  ShowPostNavLinks = true
  disableThemeToggle = false

[outputs]
  home = [ "HTML", "RSS", "JSON" ]